# Generated by Django 5.2.7 on 2025-10-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_non_negative_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='price_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='stock_count_non_negative',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_count__gt', 0)), name='stock_count_non_negative'),
        ),
    ]
